export interface Country {
  code: string
  name: string
  flag: string
}

function f(code: string): string {
  return [...code.toUpperCase()].map(c =>
    String.fromCodePoint(0x1F1E6 + c.charCodeAt(0) - 65)
  ).join('')
}

export const POPULAR_COUNTRIES: Country[] = [
  { code: 'BR', name: 'Brazil',         flag: f('BR') },
  { code: 'US', name: 'United States',  flag: f('US') },
  { code: 'GB', name: 'United Kingdom', flag: f('GB') },
  { code: 'PT', name: 'Portugal',       flag: f('PT') },
  { code: 'ES', name: 'Spain',          flag: f('ES') },
  { code: 'AR', name: 'Argentina',      flag: f('AR') },
]

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan',            flag: f('AF') },
  { code: 'AL', name: 'Albania',                flag: f('AL') },
  { code: 'DZ', name: 'Algeria',                flag: f('DZ') },
  { code: 'AD', name: 'Andorra',                flag: f('AD') },
  { code: 'AO', name: 'Angola',                 flag: f('AO') },
  { code: 'AG', name: 'Antigua and Barbuda',    flag: f('AG') },
  { code: 'AR', name: 'Argentina',              flag: f('AR') },
  { code: 'AM', name: 'Armenia',                flag: f('AM') },
  { code: 'AU', name: 'Australia',              flag: f('AU') },
  { code: 'AT', name: 'Austria',                flag: f('AT') },
  { code: 'AZ', name: 'Azerbaijan',             flag: f('AZ') },
  { code: 'BS', name: 'Bahamas',                flag: f('BS') },
  { code: 'BH', name: 'Bahrain',                flag: f('BH') },
  { code: 'BD', name: 'Bangladesh',             flag: f('BD') },
  { code: 'BB', name: 'Barbados',               flag: f('BB') },
  { code: 'BY', name: 'Belarus',                flag: f('BY') },
  { code: 'BE', name: 'Belgium',                flag: f('BE') },
  { code: 'BZ', name: 'Belize',                 flag: f('BZ') },
  { code: 'BJ', name: 'Benin',                  flag: f('BJ') },
  { code: 'BT', name: 'Bhutan',                 flag: f('BT') },
  { code: 'BO', name: 'Bolivia',                flag: f('BO') },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: f('BA') },
  { code: 'BW', name: 'Botswana',               flag: f('BW') },
  { code: 'BR', name: 'Brazil',                 flag: f('BR') },
  { code: 'BN', name: 'Brunei',                 flag: f('BN') },
  { code: 'BG', name: 'Bulgaria',               flag: f('BG') },
  { code: 'BF', name: 'Burkina Faso',           flag: f('BF') },
  { code: 'BI', name: 'Burundi',                flag: f('BI') },
  { code: 'CV', name: 'Cabo Verde',             flag: f('CV') },
  { code: 'KH', name: 'Cambodia',               flag: f('KH') },
  { code: 'CM', name: 'Cameroon',               flag: f('CM') },
  { code: 'CA', name: 'Canada',                 flag: f('CA') },
  { code: 'CF', name: 'Central African Rep.',   flag: f('CF') },
  { code: 'TD', name: 'Chad',                   flag: f('TD') },
  { code: 'CL', name: 'Chile',                  flag: f('CL') },
  { code: 'CN', name: 'China',                  flag: f('CN') },
  { code: 'CO', name: 'Colombia',               flag: f('CO') },
  { code: 'KM', name: 'Comoros',                flag: f('KM') },
  { code: 'CG', name: 'Congo',                  flag: f('CG') },
  { code: 'CD', name: 'Congo, D.R.',            flag: f('CD') },
  { code: 'CR', name: 'Costa Rica',             flag: f('CR') },
  { code: 'HR', name: 'Croatia',                flag: f('HR') },
  { code: 'CU', name: 'Cuba',                   flag: f('CU') },
  { code: 'CY', name: 'Cyprus',                 flag: f('CY') },
  { code: 'CZ', name: 'Czech Republic',         flag: f('CZ') },
  { code: 'DK', name: 'Denmark',                flag: f('DK') },
  { code: 'DJ', name: 'Djibouti',               flag: f('DJ') },
  { code: 'DM', name: 'Dominica',               flag: f('DM') },
  { code: 'DO', name: 'Dominican Republic',     flag: f('DO') },
  { code: 'EC', name: 'Ecuador',                flag: f('EC') },
  { code: 'EG', name: 'Egypt',                  flag: f('EG') },
  { code: 'SV', name: 'El Salvador',            flag: f('SV') },
  { code: 'GQ', name: 'Equatorial Guinea',      flag: f('GQ') },
  { code: 'ER', name: 'Eritrea',                flag: f('ER') },
  { code: 'EE', name: 'Estonia',                flag: f('EE') },
  { code: 'SZ', name: 'Eswatini',               flag: f('SZ') },
  { code: 'ET', name: 'Ethiopia',               flag: f('ET') },
  { code: 'FJ', name: 'Fiji',                   flag: f('FJ') },
  { code: 'FI', name: 'Finland',                flag: f('FI') },
  { code: 'FR', name: 'France',                 flag: f('FR') },
  { code: 'GA', name: 'Gabon',                  flag: f('GA') },
  { code: 'GM', name: 'Gambia',                 flag: f('GM') },
  { code: 'GE', name: 'Georgia',                flag: f('GE') },
  { code: 'DE', name: 'Germany',                flag: f('DE') },
  { code: 'GH', name: 'Ghana',                  flag: f('GH') },
  { code: 'GR', name: 'Greece',                 flag: f('GR') },
  { code: 'GD', name: 'Grenada',                flag: f('GD') },
  { code: 'GT', name: 'Guatemala',              flag: f('GT') },
  { code: 'GN', name: 'Guinea',                 flag: f('GN') },
  { code: 'GW', name: 'Guinea-Bissau',          flag: f('GW') },
  { code: 'GY', name: 'Guyana',                 flag: f('GY') },
  { code: 'HT', name: 'Haiti',                  flag: f('HT') },
  { code: 'HN', name: 'Honduras',               flag: f('HN') },
  { code: 'HU', name: 'Hungary',                flag: f('HU') },
  { code: 'IS', name: 'Iceland',                flag: f('IS') },
  { code: 'IN', name: 'India',                  flag: f('IN') },
  { code: 'ID', name: 'Indonesia',              flag: f('ID') },
  { code: 'IR', name: 'Iran',                   flag: f('IR') },
  { code: 'IQ', name: 'Iraq',                   flag: f('IQ') },
  { code: 'IE', name: 'Ireland',                flag: f('IE') },
  { code: 'IL', name: 'Israel',                 flag: f('IL') },
  { code: 'IT', name: 'Italy',                  flag: f('IT') },
  { code: 'JM', name: 'Jamaica',                flag: f('JM') },
  { code: 'JP', name: 'Japan',                  flag: f('JP') },
  { code: 'JO', name: 'Jordan',                 flag: f('JO') },
  { code: 'KZ', name: 'Kazakhstan',             flag: f('KZ') },
  { code: 'KE', name: 'Kenya',                  flag: f('KE') },
  { code: 'KI', name: 'Kiribati',               flag: f('KI') },
  { code: 'KW', name: 'Kuwait',                 flag: f('KW') },
  { code: 'KG', name: 'Kyrgyzstan',             flag: f('KG') },
  { code: 'LA', name: 'Laos',                   flag: f('LA') },
  { code: 'LV', name: 'Latvia',                 flag: f('LV') },
  { code: 'LB', name: 'Lebanon',                flag: f('LB') },
  { code: 'LS', name: 'Lesotho',                flag: f('LS') },
  { code: 'LR', name: 'Liberia',                flag: f('LR') },
  { code: 'LY', name: 'Libya',                  flag: f('LY') },
  { code: 'LI', name: 'Liechtenstein',          flag: f('LI') },
  { code: 'LT', name: 'Lithuania',              flag: f('LT') },
  { code: 'LU', name: 'Luxembourg',             flag: f('LU') },
  { code: 'MG', name: 'Madagascar',             flag: f('MG') },
  { code: 'MW', name: 'Malawi',                 flag: f('MW') },
  { code: 'MY', name: 'Malaysia',               flag: f('MY') },
  { code: 'MV', name: 'Maldives',               flag: f('MV') },
  { code: 'ML', name: 'Mali',                   flag: f('ML') },
  { code: 'MT', name: 'Malta',                  flag: f('MT') },
  { code: 'MH', name: 'Marshall Islands',       flag: f('MH') },
  { code: 'MR', name: 'Mauritania',             flag: f('MR') },
  { code: 'MU', name: 'Mauritius',              flag: f('MU') },
  { code: 'MX', name: 'Mexico',                 flag: f('MX') },
  { code: 'FM', name: 'Micronesia',             flag: f('FM') },
  { code: 'MD', name: 'Moldova',                flag: f('MD') },
  { code: 'MC', name: 'Monaco',                 flag: f('MC') },
  { code: 'MN', name: 'Mongolia',               flag: f('MN') },
  { code: 'ME', name: 'Montenegro',             flag: f('ME') },
  { code: 'MA', name: 'Morocco',                flag: f('MA') },
  { code: 'MZ', name: 'Mozambique',             flag: f('MZ') },
  { code: 'MM', name: 'Myanmar',                flag: f('MM') },
  { code: 'NA', name: 'Namibia',                flag: f('NA') },
  { code: 'NR', name: 'Nauru',                  flag: f('NR') },
  { code: 'NP', name: 'Nepal',                  flag: f('NP') },
  { code: 'NL', name: 'Netherlands',            flag: f('NL') },
  { code: 'NZ', name: 'New Zealand',            flag: f('NZ') },
  { code: 'NI', name: 'Nicaragua',              flag: f('NI') },
  { code: 'NE', name: 'Niger',                  flag: f('NE') },
  { code: 'NG', name: 'Nigeria',                flag: f('NG') },
  { code: 'KP', name: 'North Korea',            flag: f('KP') },
  { code: 'MK', name: 'North Macedonia',        flag: f('MK') },
  { code: 'NO', name: 'Norway',                 flag: f('NO') },
  { code: 'OM', name: 'Oman',                   flag: f('OM') },
  { code: 'PK', name: 'Pakistan',               flag: f('PK') },
  { code: 'PW', name: 'Palau',                  flag: f('PW') },
  { code: 'PA', name: 'Panama',                 flag: f('PA') },
  { code: 'PG', name: 'Papua New Guinea',       flag: f('PG') },
  { code: 'PY', name: 'Paraguay',               flag: f('PY') },
  { code: 'PE', name: 'Peru',                   flag: f('PE') },
  { code: 'PH', name: 'Philippines',            flag: f('PH') },
  { code: 'PL', name: 'Poland',                 flag: f('PL') },
  { code: 'PT', name: 'Portugal',               flag: f('PT') },
  { code: 'QA', name: 'Qatar',                  flag: f('QA') },
  { code: 'RO', name: 'Romania',                flag: f('RO') },
  { code: 'RU', name: 'Russia',                 flag: f('RU') },
  { code: 'RW', name: 'Rwanda',                 flag: f('RW') },
  { code: 'KN', name: 'Saint Kitts and Nevis',  flag: f('KN') },
  { code: 'LC', name: 'Saint Lucia',            flag: f('LC') },
  { code: 'VC', name: 'Saint Vincent',          flag: f('VC') },
  { code: 'WS', name: 'Samoa',                  flag: f('WS') },
  { code: 'SM', name: 'San Marino',             flag: f('SM') },
  { code: 'ST', name: 'São Tomé and Príncipe',  flag: f('ST') },
  { code: 'SA', name: 'Saudi Arabia',           flag: f('SA') },
  { code: 'SN', name: 'Senegal',                flag: f('SN') },
  { code: 'RS', name: 'Serbia',                 flag: f('RS') },
  { code: 'SC', name: 'Seychelles',             flag: f('SC') },
  { code: 'SL', name: 'Sierra Leone',           flag: f('SL') },
  { code: 'SG', name: 'Singapore',              flag: f('SG') },
  { code: 'SK', name: 'Slovakia',               flag: f('SK') },
  { code: 'SI', name: 'Slovenia',               flag: f('SI') },
  { code: 'SB', name: 'Solomon Islands',        flag: f('SB') },
  { code: 'SO', name: 'Somalia',                flag: f('SO') },
  { code: 'ZA', name: 'South Africa',           flag: f('ZA') },
  { code: 'KR', name: 'South Korea',            flag: f('KR') },
  { code: 'SS', name: 'South Sudan',            flag: f('SS') },
  { code: 'ES', name: 'Spain',                  flag: f('ES') },
  { code: 'LK', name: 'Sri Lanka',              flag: f('LK') },
  { code: 'SD', name: 'Sudan',                  flag: f('SD') },
  { code: 'SR', name: 'Suriname',               flag: f('SR') },
  { code: 'SE', name: 'Sweden',                 flag: f('SE') },
  { code: 'CH', name: 'Switzerland',            flag: f('CH') },
  { code: 'SY', name: 'Syria',                  flag: f('SY') },
  { code: 'TW', name: 'Taiwan',                 flag: f('TW') },
  { code: 'TJ', name: 'Tajikistan',             flag: f('TJ') },
  { code: 'TZ', name: 'Tanzania',               flag: f('TZ') },
  { code: 'TH', name: 'Thailand',               flag: f('TH') },
  { code: 'TL', name: 'Timor-Leste',            flag: f('TL') },
  { code: 'TG', name: 'Togo',                   flag: f('TG') },
  { code: 'TO', name: 'Tonga',                  flag: f('TO') },
  { code: 'TT', name: 'Trinidad and Tobago',    flag: f('TT') },
  { code: 'TN', name: 'Tunisia',                flag: f('TN') },
  { code: 'TR', name: 'Turkey',                 flag: f('TR') },
  { code: 'TM', name: 'Turkmenistan',           flag: f('TM') },
  { code: 'TV', name: 'Tuvalu',                 flag: f('TV') },
  { code: 'UG', name: 'Uganda',                 flag: f('UG') },
  { code: 'UA', name: 'Ukraine',                flag: f('UA') },
  { code: 'AE', name: 'United Arab Emirates',   flag: f('AE') },
  { code: 'GB', name: 'United Kingdom',         flag: f('GB') },
  { code: 'US', name: 'United States',          flag: f('US') },
  { code: 'UY', name: 'Uruguay',                flag: f('UY') },
  { code: 'UZ', name: 'Uzbekistan',             flag: f('UZ') },
  { code: 'VU', name: 'Vanuatu',                flag: f('VU') },
  { code: 'VE', name: 'Venezuela',              flag: f('VE') },
  { code: 'VN', name: 'Vietnam',                flag: f('VN') },
  { code: 'YE', name: 'Yemen',                  flag: f('YE') },
  { code: 'ZM', name: 'Zambia',                 flag: f('ZM') },
  { code: 'ZW', name: 'Zimbabwe',               flag: f('ZW') },
]
