/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    borderRadius: {
      none:    '0px',
      DEFAULT: '0px',
      sm:      '0px',
      md:      '0px',
      lg:      '0px',
      xl:      '0px',
      '2xl':   '0px',
      '3xl':   '0px',
      full:    '9999px',
    },
    boxShadow: {
      none:    'none',
      DEFAULT: 'none',
      sm:      'none',
      md:      'none',
      lg:      'none',
      xl:      'none',
      '2xl':   'none',
      inner:   'inset 0 1px 0 0 rgba(255,255,255,0.05)',
    },
    extend: {
      colors: {
        graphite:      '#0A0A0A',
        card:          '#141414',
        'card-raised':  '#1F1F1F',
        'card-hover':   '#2A2A2A',
        'soft-white':   '#F5F5F0',
        'sub-gray':     '#6B6B68',
        'dis-gray':     '#3D3D3B',
        'muted-gray':   '#A8A8A4',
        lime:           '#D4FF3A',
        'lime-hi':      '#E5FF6B',
        'lime-lo':      '#A6CC2E',
        'lime-ink':     '#0A0A0A',
        success:        '#D4FF3A',
        warning:        '#FFB800',
        danger:         '#FF3B30',
        info:           '#4DA3FF',
        'perf-blue':    '#4DA3FF',
        'border-base':  '#2A2A2A',
        'border-mid':   '#3D3D3B',
        'border-hi':    '#595956',
      },
      fontFamily: {
        sans: ['"Space Grotesk"', '"Helvetica Neue"', 'Helvetica', 'Arial', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', '"SF Mono"', 'Menlo', 'monospace'],
      },
    },
  },
  plugins: [],
}
